JDP220801-20 UserTestSuite
piotr-grosicki/project-jdp-2208-01 pull request #28
Opened 2022-08-04 16:51 UTC by HubertJarzynka

2022-08-04 23:21 UTC, marcinpaszenda commented on src/test/java/com/kodilla/ecommercee/domain/UserTestSuite.java
> +        user.setContent(true);
Nie wiem czy jest potrzeba ustawiania wszystkich pól, ale w sumie na potrzeby testowania można tak zrobić.

2022-08-04 23:21 UTC, marcinpaszenda commented on src/test/java/com/kodilla/ecommercee/domain/UserTestSuite.java
> +        assertTrue(userRepository.findByContent(user.getContent()).isPresent());
To dla pewności zrobiłbym assertEquals.

2022-08-04 23:23 UTC, marcinpaszenda commented on src/test/java/com/kodilla/ecommercee/domain/UserTestSuite.java
> +
Brakuje jeszcze testów relacji ;)

2022-08-04 23:26 UTC, marcinpaszenda reviewed
Komentarze dołączone w kodzie

2022-08-05 07:49 UTC, weronikamartamalicka commented on src/main/java/com/kodilla/ecommercee/repository/UserRepository.java
> +    Optional<User> findById(Long id);
Jak nadpisujesz metodę to możesz zmienić typ zwracany na User, chyba że to specjalny zabieg to w ogóle nie musisz nadpisywać bo ta metoda jest już w interfejsie Crud

2022-08-05 07:50 UTC, weronikamartamalicka commented on src/main/java/com/kodilla/ecommercee/repository/UserRepository.java
> +    void deleteById(Long id);
Tej metody też nie trzeba nadpisywać bo ona już jest w interfejsie Crud, więc jak go rozszerzasz to też masz dostępną tą metodę

2022-08-05 07:51 UTC, weronikamartamalicka commented on src/test/java/com/kodilla/ecommercee/domain/UserTestSuite.java
> +    public void FindUserByAllFieldsTest() {
Fajny pomysł na metodę testową :)

2022-08-05 07:52 UTC, weronikamartamalicka commented on src/test/java/com/kodilla/ecommercee/domain/UserTestSuite.java
> +    public void userTest() {
Ja bym inaczej nazwała tą metodę, bo ona nie testuje nic. Może lepiej byłoby nazwać ją prepareData()?

2022-08-05 07:55 UTC, weronikamartamalicka requested changes
Tak jak Marcin napisał, brakuje testów relacji, czyli User ma relację z Cart(1-1) i Order(1-N) więc tutaj musisz sprawdzić czy te relacje działają prawidłowo. Na razie masz sprawdzone zapisywanie i wyszukiwanie i też w sumie usuwanie :)

2022-08-05 15:15 UTC, TobiaszCh requested changes
tak jak ekipa pisze wyzej czekam na poprawki ;) 
jakbys potrzebowal pomocy to smialo pisz :D

2022-08-05 15:51 UTC, HubertJarzynka commented on src/test/java/com/kodilla/ecommercee/domain/UserTestSuite.java
> +    public void userTest() {
Dziękuję za podpowiedź kompletnie nie miałem inwencji jak to nazwać!

2022-08-05 15:58 UTC, HubertJarzynka commented on src/main/java/com/kodilla/ecommercee/repository/UserRepository.java
> +    void deleteById(Long id);
Niestety u mnie to tak nie działało. Zostawiam tylko metodę findAll() bo bez tego nie działa mi test findUsersTests

2022-08-05 17:36 UTC, Mihuul approved these changes

2022-08-08 13:31 UTC, weronikamartamalicka reviewed
Jeśli testy przechodzą pomimo tego podwójnego "zapisania" to dla mnie spoko, jak chce Ci się poprawić to co napisałam to też ok

2022-08-08 13:31 UTC, weronikamartamalicka commented on src/test/java/com/kodilla/ecommercee/domain/UserTestSuite.java
> +    public void checkIfCartIsSavedTest() {
Ja bym może inaczej nazwała test, bo jednak testujesz relacje a nie czy się zapisuje - czyli na przykład testUserCartRelation()

2022-08-08 13:31 UTC, weronikamartamalicka commented on src/test/java/com/kodilla/ecommercee/domain/UserTestSuite.java
> +        userRepository.save(user);
Jak zapisałeś usera w repozytorium to nie musisz dodawać order, bo user sam powinien Ci ten order zapisać jeśli jest pomiędzy nimi relacja. Hibernate nie wywalił Ci tu błędu jak puszczałeś testy?

2022-08-08 13:31 UTC, weronikamartamalicka commented on src/test/java/com/kodilla/ecommercee/domain/UserTestSuite.java
> +    public void checkIfCartIsSavedTest() {
No ale nie będę się czepiać o nazwy :p

2022-08-08 13:31 UTC, weronikamartamalicka commented on src/test/java/com/kodilla/ecommercee/domain/UserTestSuite.java
> +        Assertions.assertFalse(orderRepository.findById(order.getId()).isPresent());
Fajny pomysł na metodę :)

2022-08-08 19:25 UTC, HubertJarzynka commented on src/test/java/com/kodilla/ecommercee/domain/UserTestSuite.java
> +        userRepository.save(user);
czysto bez błędów więc zostawiam.

2022-08-08 19:28 UTC, HubertJarzynka commented on src/test/java/com/kodilla/ecommercee/domain/UserTestSuite.java
> +    public void checkIfCartIsSavedTest() {
nazwa poprawiona :)

2022-08-09 07:11 UTC, TobiaszCh approved these changes

2022-08-09 07:22 UTC, weronikamartamalicka commented on src/main/java/com/kodilla/ecommercee/repository/UserRepository.java
> +    void deleteById(Long id);
Może to przez typ zwracany, bo findAll() zwraca Iterable<T> z tego co pamiętam? Tak czy inaczej nadpisanie tej metody tutaj jest spoko :) Jak kto woli

2022-08-09 07:23 UTC, weronikamartamalicka commented on src/test/java/com/kodilla/ecommercee/domain/UserTestSuite.java
> +        userRepository.save(user);
To jak sobie zrobię pull z main to z ciekawości potestuję bo mi zawsze wywalało błąd w tym miejscu :) Ale jak działa to zostaw oczywiście

2022-08-09 07:24 UTC, weronikamartamalicka approved these changes

2022-08-09 07:25 UTC, weronikamartamalicka commented
@marcinpaszenda  chyba jeszcze Twojego approva brakuje :) Nie chcę mergować dopóki wszyscy zapisani nie przejrzą

2022-08-09 15:41 UTC, merged