JDP220801-21
piotr-grosicki/project-jdp-2208-01 pull request #29
Opened 2022-08-05 10:33 UTC by Kamil-Kwiecinski

2022-08-08 18:54 UTC, Kamil-Kwiecinski commented
Halo halo? Ktoś na to patrzył? Jakieś uwagi?

2022-08-08 22:06 UTC, marcinpaszenda commented
> Halo halo? Ktoś na to patrzył? Jakieś uwagi?

Cześć. Zerkam :)

2022-08-08 22:39 UTC, marcinpaszenda commented on gradlew.bat
>  @rem End local scope for the variables with windows NT shell
Hmm, nie bardzo wiem, z czego wynikają zmiany w plikach gradle-wrappers.properties, gradlew i gradlew.bat. Jeśli to nie przypadkowe działanie to napisz o co chodzi.

2022-08-08 22:39 UTC, marcinpaszenda commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
>          return new ArrayList<>();
Tutaj masz metodę bez implementacji mapowania. Musisz ją zrobić.

2022-08-08 22:39 UTC, marcinpaszenda commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +       productDbService.saveProduct(productMapper.mapToProduct(productDto));
Tu masz void. Ta metoda nic nie zwraca. A powinna zwracać Product. 

W poniższych metodach updateProduct i deleteProduct nie ma implementacji mapowania.

2022-08-08 22:39 UTC, marcinpaszenda commented on src/main/java/com/kodilla/ecommercee/service/ProductDbService.java
> +    }
Brakuje implementacji serwisów dla findAll() i deleteById() :)

2022-08-09 07:40 UTC, weronikamartamalicka requested changes

2022-08-09 07:40 UTC, weronikamartamalicka commented on src/main/java/com/kodilla/ecommercee/mapper/ProductMapper.java
> +        return new Product(
Tak się zastanawiam czy to specjalny zabieg, że tutaj nie ma id? Wydaje mi się, że lepiej nad kolumną z id usunąć adnotację @NotNull i zmapować tutaj wszystko

2022-08-09 07:40 UTC, weronikamartamalicka commented on src/main/java/com/kodilla/ecommercee/mapper/ProductMapper.java
> +                        .map(Order::getId)
Tutaj odwołując się do metody getId zamieniasz obiekty na ich id, a pewnie nie o to chodziło :) W ogóle myślę, że jeśli jest relacja pomiędzy Product i Order to nie trzeba ich "szukać" po id

2022-08-09 07:40 UTC, weronikamartamalicka commented on src/main/java/com/kodilla/ecommercee/mapper/ProductMapper.java
> +                product.getOrders().stream()
Tutaj też dałabym "zabezpieczenie" w postaci Collections.emptyList() jeśli ta lista jest nulem

2022-08-09 07:40 UTC, weronikamartamalicka commented on src/main/java/com/kodilla/ecommercee/mapper/ProductMapper.java
> +                product.getCarts().stream()
Tutaj podobnie jak wyżej

2022-08-09 07:40 UTC, weronikamartamalicka commented on src/main/java/com/kodilla/ecommercee/service/ProductDbService.java
> +        return productRepository.findById(id).get();
Nie rozumiem tego get() na końcu? Tutaj też(jeśli będzie na to czas) zabezpieczyłabym się metodą klasy Optional orElseThrow() na wypadek gdy nie będzie tego id

2022-08-09 07:40 UTC, weronikamartamalicka commented on src/main/java/com/kodilla/ecommercee/mapper/ProductMapper.java
> +                product.getGroup().getId(),
Nie rozumiem zamiany obiektu Group na id

2022-08-09 07:46 UTC, Kamil-Kwiecinski commented on gradlew.bat
>  @rem End local scope for the variables with windows NT shell
Nie budował mi się projekt. Rozwiązaniem problemu okazała się formuła: gradle wrapper --gradle-version 7.0.2
Tutaj link do calości tematu: https://chat.kodilla.com/group/help-java?msg=KdxqPX5DtqPuPhXmv
Nie wydaję mi się, żeby to miało wpływ na projekt.

2022-08-09 09:44 UTC, Kamil-Kwiecinski commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +       productDbService.saveProduct(productMapper.mapToProduct(productDto));
updateProduct ma być void? createProduct już poprawiłem.

2022-08-09 09:48 UTC, Kamil-Kwiecinski commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
>          return new ArrayList<>();
Zrobione. Będzie w commicie.

2022-08-09 09:56 UTC, Kamil-Kwiecinski commented on src/main/java/com/kodilla/ecommercee/service/ProductDbService.java
> +        return productRepository.findById(id).get();
Poprawione. Dodałem nową klasę ProductNotFoundExpection.

2022-08-09 17:01 UTC, Kamil-Kwiecinski commented
Okej. Wrzuciłem commita. Sprawdźcie proszę teraz ;) Wciąż nie jestem pewien jak zrobić to "Collections.emptyList()" co pisała Weronika.

2022-08-09 20:28 UTC, marcinpaszenda commented on gradlew.bat
>  @rem End local scope for the variables with windows NT shell
No właśnie nie jestem do końca przekonany czy czasem to nie wpłynie na projekt.

2022-08-09 20:29 UTC, marcinpaszenda commented on src/main/java/com/kodilla/ecommercee/service/ProductDbService.java
> +}
Jest oki!

2022-08-09 20:37 UTC, Kamil-Kwiecinski commented on src/main/java/com/kodilla/ecommercee/service/ProductDbService.java
> +}
To teraz pytanie jak mam to wrzucić bez tych plików gradle :D...

2022-08-09 21:00 UTC, marcinpaszenda commented on src/main/java/com/kodilla/ecommercee/service/ProductDbService.java
> +}
Możesz to robić ręcznie przed commitem, nie dodając wszystkiego poleceniem "git add ." tylko ręcznie dodawać każdy plik który chcesz wrzucić poleceniem "git add ŚCIEŻKA" pomijając te, których nie chcesz wysłać. Możesz też ułatwić sobie sprawę i wrzucić te pliki do gitignore. :)
https://www.zoraclemipodrodze.pl/git-praca-na-zmianach/

2022-08-10 07:26 UTC, weronikamartamalicka commented on src/main/java/com/kodilla/ecommercee/service/ProductDbService.java
> +}
Ja też robię najpierw git status i mi wyświetla od razu ścieżki, które zmieniałam :)Tylko że nie wiem czy Ci da zrobić PR brancha na którym są niescomitowane zmiany? Mi kiedyś krzyczał

2022-08-10 07:32 UTC, weronikamartamalicka approved these changes
Jak dla mnie super zrobione :) Dodałabym tylko w mapowaniu Product, żeby miał pole id no i te pliki gradle trochę się nimi stresuję :p A tymi pustymi listami się nie martw, to jak będzie czas

2022-08-10 22:57 UTC, marcinpaszenda commented
> Jak dla mnie super zrobione :) Dodałabym tylko w mapowaniu Product, żeby miał pole id no i te pliki gradle trochę się nimi stresuję :p A tymi pustymi listami się nie martw, to jak będzie czas

No właśnie, merge'ujemy te pliki gradle?

2022-08-11 08:43 UTC, Kamil-Kwiecinski commented
Tymi plikami gradle już się zająłem. Tylko tego binarnego nie mogę zmienić. To co? Merge?

2022-08-11 12:43 UTC, weronikamartamalicka commented
Jak dla mnie lepiej zmergować i najwyżej poprawimy :p

2022-08-11 15:25 UTC, HubertJarzynka approved these changes
Ja bym to przepchnął u mnie projekt działa poprawnie i ogólnie wygląda to ok.

2022-08-11 17:26 UTC, merged