Add OrderConntroller
piotr-grosicki/project-jdp-2208-01 pull request #3
Opened 2022-07-24 21:36 UTC by marcinpaszenda

2022-07-25 11:37 UTC, piotr-grosicki requested changes
branch main zostal zmieniony - pojawily sie konflikty https://www.jetbrains.com/help/idea/resolve-conflicts.html

2022-07-25 22:08 UTC, marcinpaszenda commented
Rozwiązałem konflikty. Teraz powinno być okay

2022-07-26 08:20 UTC, piotr-grosicki requested changes

2022-07-26 08:20 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +public class Order {
w tym zadaniu nie powinna powstac encja, dla encji jest osobne zadanie

2022-07-26 17:49 UTC, closed without merging