JDP220801-24 OrderController implementacja wstępna
piotr-grosicki/project-jdp-2208-01 pull request #30
Opened 2022-08-07 21:42 UTC by marcinpaszenda

Implementacja wstępna. Po pojawieniu się reszty mapperów i serwisów dokończę mapowanie.

2022-08-08 17:13 UTC, Mihuul requested changes
Oprócz takich drobnych rzeczy, to jak dla mnie jest dobrze. 
Ale na wszelki wypadek niech ktoś jeszcze zerknie

2022-08-08 17:13 UTC, Mihuul commented on src/main/java/com/kodilla/ecommercee/repository/OrderRepository.java
> +import javax.crypto.spec.OAEPParameterSpec;
U mnie pokazuje że jest to nieużywany import. Jeżeli kiedyś będzie używany to super jak nie to możesz usunąć.

2022-08-08 17:13 UTC, Mihuul commented on src/main/java/com/kodilla/ecommercee/repository/OrderRepository.java
> +import java.util.Optional;
Tutaj to samo co wyżej

2022-08-08 17:13 UTC, Mihuul commented on src/main/java/com/kodilla/ecommercee/service/DbOrderService.java
> +    }
Żeby trochę skrócić kod można zastąpić konstruktor adnotacją @RequiredArgsConstructor. Zawsze trochę czytelniej :)

2022-08-08 17:13 UTC, Mihuul commented on src/main/java/com/kodilla/ecommercee/service/DbOrderService.java
> +    private final OrderRepository orderRepository;
Dodaj adnotację @Autowired

2022-08-08 19:36 UTC, HubertJarzynka commented on src/main/java/com/kodilla/ecommercee/repository/OrderRepository.java
> +import java.util.Optional;
dokładnie mam tak samo

2022-08-08 21:37 UTC, marcinpaszenda commented on src/main/java/com/kodilla/ecommercee/repository/OrderRepository.java
> +import java.util.Optional;
Importy ukryły mi się pod trzykropkiem w intelliJ i nie zauważyłem ich. Macie rację, te dwa importy są do wywalenia.

2022-08-08 21:38 UTC, marcinpaszenda commented on src/main/java/com/kodilla/ecommercee/service/DbOrderService.java
> +    }
Można, prawda! :)

2022-08-08 21:38 UTC, marcinpaszenda commented on src/main/java/com/kodilla/ecommercee/service/DbOrderService.java
> +    private final OrderRepository orderRepository;
Racja!

2022-08-08 23:36 UTC, marcinpaszenda commented on src/main/java/com/kodilla/ecommercee/service/DbOrderService.java
> +    private final OrderRepository orderRepository;
![Zrzut ekranu 2022-08-9 o 01 34 18](https://user-images.githubusercontent.com/98706419/183532192-0095759d-b7d9-4109-9fac-7611e5ac5e9a.png)

Jednak @Autowired jest zbędne tutaj

2022-08-09 07:58 UTC, weronikamartamalicka commented on src/main/java/com/kodilla/ecommercee/controller/OrderController.java
> +    private final DbOrderService orderService;
Krócej jest wstrzykiwać zależność poprzez pole klasy z adnotacją @Autowired, ale jeśli chcesz przez konstruktor to też działa

2022-08-09 07:58 UTC, weronikamartamalicka commented on src/main/java/com/kodilla/ecommercee/service/DbOrderService.java
> +    private final OrderRepository orderRepository;
IntelliJ Ci tutaj mówi że nie jest rekomendowane, ale jest konieczne,no musisz wstrzyknąć zależność jakoś. Możesz to zrobić przez konstruktor jeśli chcesz. Apka Ci ruszyła bez tej adnotacji?

2022-08-09 17:12 UTC, Kamil-Kwiecinski approved these changes

2022-08-09 17:28 UTC, Kamil-Kwiecinski commented on src/main/java/com/kodilla/ecommercee/exceptions/OrderNotFoundException.java
> +
public OrderNotFoundException (String message) {
        super(message);
    }
    
    Coś takiego

2022-08-09 20:03 UTC, marcinpaszenda commented on src/main/java/com/kodilla/ecommercee/controller/OrderController.java
> +    private final DbOrderService orderService;
:)

2022-08-09 23:22 UTC, marcinpaszenda commented
Dodałem ResponseEntity, globalną obsługę wyjątków, w DbOrderService metodę updateOrder, wedle Waszego życzenia usunąłem konstruktor i zastąpiłem go adnotacją lomboka.

2022-08-10 07:37 UTC, weronikamartamalicka approved these changes
Jak dla mnie spoko :)!

2022-08-10 07:37 UTC, weronikamartamalicka commented on src/main/java/com/kodilla/ecommercee/service/DbOrderService.java
> +    private final OrderRepository orderRepository;
Tutaj tylko IntelliJ Ci mówi, że wstrzykiwanie poprzez pole nie jest zalecane, ale tak mnie od wczoraj zastanawia, skąd Spring wie że ma tu wstrzyknąć obiekt repozytorium? Mam tak samo w projekcie Kodilli i zgłupiałam :P

2022-08-10 07:38 UTC, weronikamartamalicka commented
@Mihuul i @HubertJarzynka musicie jeszcze dać approve żebyśmy zmergowali

2022-08-10 23:02 UTC, marcinpaszenda commented
> @Mihuul i @HubertJarzynka musicie jeszcze dać approve żebyśmy zmergowali

Jak jest ok to czekamy na potwierdzenie ;)

2022-08-11 06:58 UTC, Mihuul reviewed
W sumie nie licząc pytania o ten kontroler to w sumie nie mam już nic więcej tutaj do dodania

2022-08-11 06:58 UTC, Mihuul commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +    }
Trochę nie rozumiem po co są tutaj te dwa konstruktory.

2022-08-11 07:24 UTC, Mihuul commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +@Builder
Nie widzę żeby ta adnotacja była gdzieś używana.

2022-08-11 07:24 UTC, Mihuul commented on src/main/java/com/kodilla/ecommercee/mapper/OrderMapper.java
> +                orderDto.getExecution()
Nie mapujemy elementów z relacji ?

2022-08-11 07:24 UTC, Mihuul commented on src/main/java/com/kodilla/ecommercee/mapper/OrderMapper.java
> +                order.getExecution()
Tutaj to samo pytanie, trochę się to wiąże z ilością konstruktorów w klasie Order

2022-08-11 09:13 UTC, marcinpaszenda commented on src/main/java/com/kodilla/ecommercee/mapper/OrderMapper.java
> +                orderDto.getExecution()
Hej. Tak jak wspominałem, zmapuje jak pojawią się pozostałe serwisy i mapery wymagane do relacji :)

2022-08-11 09:16 UTC, marcinpaszenda commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +    }
Z tego co pamiętam tak na szybko były chyba potrzebne przy testach.

2022-08-11 09:30 UTC, Mihuul approved these changes
To w takim razie wszystko wygląda git jak dla mnie

2022-08-11 12:40 UTC, weronikamartamalicka commented
@HubertJarzynka czekamy jeszcze na Twojego approv'a :) Jeśli chodzi o implementację reszty mapperów, to raczej nie będzie potrzebna, bo w DTO przechowujemy tylko id wynikające z relacji, a nie same obiekty. Pisałam chyba na początku tygodnia o tym na grupie, ale nie pamiętam :( Tak czy inaczej jest gotowe do merge :)

2022-08-11 15:10 UTC, HubertJarzynka approved these changes

2022-08-11 15:57 UTC, merged