JDP220801-18
piotr-grosicki/project-jdp-2208-01 pull request #35
Opened 2022-08-11 09:07 UTC by Kamil-Kwiecinski

2022-08-11 12:38 UTC, weronikamartamalicka requested changes
Zapisywanie, szukanie przetestowane, ale brakuje testowania relacji z Product :)

2022-08-11 12:43 UTC, Mihuul reviewed
Jeżeli będziesz dodawał test relacji z Product tak jak pisała Weronika, to ja bym tylko zaproponował stworzenie obiektów group i product po za testami. Tutaj faktycznie ich wiele nie ma, ale zawsze trochę oczyści to kod. Po za tym to wszystko wygląda dobrze.

2022-08-12 08:21 UTC, weronikamartamalicka commented
Konflikty :(

2022-08-12 09:30 UTC, Kamil-Kwiecinski commented
Właśnie wrzuciłem ten test. Dajcie znać czy to o to chodziło.

2022-08-12 09:39 UTC, Mihuul commented
Nie builduje się projekt w takiej formie. W raporcie jest wyskakuje info że jest problem z testem GroupTestSuite

2022-08-12 11:46 UTC, TobiaszCh requested changes
Projekt sie nie buduje
Konflikty

2022-08-12 13:00 UTC, Kamil-Kwiecinski commented
Konflikty też rozwiązane.

2022-08-14 20:11 UTC, TobiaszCh approved these changes

2022-08-15 07:38 UTC, weronikamartamalicka approved these changes
Dla mnie wszystko ok :)

2022-08-15 07:39 UTC, merged