Jdp220801 23pop
piotr-grosicki/project-jdp-2208-01 pull request #38
Opened 2022-08-12 23:22 UTC by TobiaszCh

2022-08-12 23:26 UTC, TobiaszCh commented
Powiem szczerze ze nie wszystkie testy w Postmanie dzialaja ale wydaje mi sie ze jest to po prostu brak Usera, chociaz moge sie mysli (a nie mam innych pomyslow na to) wiec czekam na wasze opinie :)

2022-08-15 08:02 UTC, weronikamartamalicka requested changes
Oprócz konfliktów z mainem wszystko opisałam w kodzie :)
Tak czy inaczej super robota
A na jakiej metodzie Ci się wywala Postman?

2022-08-15 08:02 UTC, weronikamartamalicka commented on src/main/java/com/kodilla/ecommercee/mapper/CartMapper.java
> +
Brakuje mi zmapowania listy - pomiędzy Cart a Produkt jest relacja M-N więc lista będzie potrzeba w praktyce

2022-08-15 11:00 UTC, Mihuul reviewed
Jak coś to User już jest, to zrób sobie update :D.

2022-08-15 11:01 UTC, HubertJarzynka submitted a review, later dismissed
Zaktualizuj sobie maina bo wpadł duży update. Wywołuj nas na discord jak coś pomożemy.

2022-08-15 13:44 UTC, weronikamartamalicka requested changes

2022-08-15 13:44 UTC, weronikamartamalicka commented on src/main/java/com/kodilla/ecommercee/domain/dto/CartDto.java
> +    private List<Long> product;
myślę, że CartDto będzie miało takie pola :

- Long id
- Long userId
- List<Long> productsId

2022-08-15 13:44 UTC, weronikamartamalicka commented on src/main/java/com/kodilla/ecommercee/mapper/CartMapper.java
> +                productMapper.mapToProductDtoList(cart.getProducts())
mapper nie jest potrzebny- jak wstawisz sobie do Dto te pola co wymieniłam to będziesz mógł je wyciągać po id z bazy danych- zobacz nasze przykłady które są już w main

2022-08-16 02:51 UTC, TobiaszCh commented
Wstawione zgodnie z zaleceniami oprocz "Brakuje mi zmapowania listy - pomiędzy Cart a Produkt jest relacja M-N więc lista będzie potrzeba w praktyce". Jezeli nie uzywam get (ogolnego) to nie potrzebuje tego mapowania chyba ze do czegos innego sie przyda ale metody sprawdzone i dzialaja :)

2022-08-16 05:09 UTC, weronikamartamalicka approved these changes
Wydaje mi się, że teraz jest spoko

2022-08-16 07:54 UTC, Mihuul reviewed
Po za tymi dwiema drobnostkami to chyba wszystko jest git. Usuń i będzie approve

2022-08-16 07:54 UTC, Mihuul commented on src/main/java/com/kodilla/ecommercee/mapper/CartMapper.java
> +import com.kodilla.ecommercee.domain.User;
Ten import jest nie używany, to można usunąć

2022-08-16 07:54 UTC, Mihuul commented on src/main/java/com/kodilla/ecommercee/repository/UserRepository.java
>  import java.util.Optional;
Ten też jest nie używany

2022-08-16 08:14 UTC, Mihuul approved these changes
Teraz jest dobrze jak dla mnie

2022-08-16 08:16 UTC, merged