Created first implementation of UserController.
piotr-grosicki/project-jdp-2208-01 pull request #8
Opened 2022-07-25 14:43 UTC by weronikamartamalicka

-Added UserController class with simple implementation
-Added UserDto class with basic fields

2022-07-25 15:45 UTC, piotr-grosicki requested changes
Cos malo tych zmian. Tylko dto?

2022-07-25 15:53 UTC, weronikamartamalicka commented
Jacie, dzisiaj jest jakiś fatal day. Już poprawiam

2022-07-26 08:20 UTC, piotr-grosicki requested changes

2022-07-26 08:20 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/dto/UserDto.java
> +public class UserDto {
a nie umowiliscie sie na korzystanie z lomboka ?:)

2022-07-26 08:28 UTC, piotr-grosicki approved these changes

2022-07-26 08:28 UTC, merged