JDP220801-2 - fix
piotr-grosicki/project-jdp-2208-01 pull request #9
Opened 2022-07-25 16:12 UTC by HubertJarzynka

2022-07-26 08:21 UTC, piotr-grosicki requested changes

2022-07-26 08:21 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/dto/GroupDto.java
> +public class GroupDto {
czemu dto jest puste? dobrze by bylo jakby mialo jakiekolwiek pola zeby to sie dalo przetestowac

2022-07-26 14:42 UTC, HubertJarzynka commented
Jeszcze to poprawię coś jest nie tak

2022-07-27 08:17 UTC, piotr-grosicki requested changes

2022-07-27 08:17 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/dto/GroupDto.java
> +public class GroupDto {
nadal group dto jest puste, nie rozumiem czemu zresolvowales dyskusje ;)

2022-07-27 15:09 UTC, piotr-grosicki requested changes
projekt sie nie buduje

2022-07-27 15:27 UTC, merged